include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: ignore
    deprecated_member_use_from_same_package: ignore
    depend_on_referenced_packages: ignore

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_declarations: false
    prefer_const_literals_to_create_immutables: false
    curly_braces_in_flow_control_structures: false
