// ignore_for_file: lines_longer_than_80_chars
/// Manual localization — no code generation required.
class AppLocalizations {
  final String langCode;
  const AppLocalizations._(this.langCode);
  factory AppLocalizations.of(String code) => AppLocalizations._(code);

  /// True for right-to-left scripts.
  bool get isRTL => const ['ar', 'fa', 'he', 'ur'].contains(langCode);

  String _t(String key) => _strings[langCode]?[key] ?? _strings['en']![key]!;

  String get liveTV         => _t('liveTV');
  String get movies         => _t('movies');
  String get series         => _t('series');
  String get radios         => _t('radios');
  String get refresh        => _t('refresh');
  String get change         => _t('change');
  String get language       => _t('language');
  String get addPlaylist    => _t('addPlaylist');
  String get settings       => _t('settings');
  String get about          => _t('about');
  String get deviceInfo     => _t('deviceInfo');
  String get home           => _t('home');
  String get favorites      => _t('favorites');
  String get search         => _t('search');
  String get exit           => _t('exit');
  String get channels       => _t('channels');
  String get films          => _t('films');
  String get shows          => _t('shows');
  String get radioStations  => _t('radioStations');
  String get selectChannel  => _t('selectChannel');
  String get noChannels     => _t('noChannels');
  String get searchHint     => _t('searchHint');
  String get searchMovies   => _t('searchMovies');
  String get searchSeries   => _t('searchSeries');
  String get searchRadios   => _t('searchRadios');
  String get loading        => _t('loading');
  String get error          => _t('error');
  String get retry          => _t('retry');
  String get cancel         => _t('cancel');
  String get noContent      => _t('noContent');
  String get noSeries       => _t('noSeries');
  String get selectPlaylist => _t('selectPlaylist');
  String get aboutApp       => _t('aboutApp');
  String get playlistInfo   => _t('playlistInfo');
  String get tapToLoad      => _t('tapToLoad');
  String get loadingLive    => _t('loadingLive');
  String get loadingMovies  => _t('loadingMovies');
  String get loadingSeries  => _t('loadingSeries');
  String get loadingMoment  => _t('loadingMoment');
  String get noEpisodes     => _t('noEpisodes');
  String get season         => _t('season');
  String get changeLanguage => _t('changeLanguage');
  String get addPlaylistHint => _t('addPlaylistHint');
  String get playlist       => _t('playlist');
  String get info           => _t('info');
  String get tvPrograms     => _t('tvPrograms');
  String get streamError    => _t('streamError');
  String get seasons        => _t('seasons');
  String get episodes       => _t('episodes');

  // ── Translation tables ─────────────────────────────────────────────────────
  static const Map<String, Map<String, String>> _strings = {

    // ── English ───────────────────────────────────────────────────────────────
    'en': {
      'liveTV':         'Live TV',
      'movies':         'Movies',
      'series':         'Series',
      'radios':         'Radios',
      'refresh':        'Refresh',
      'change':         'Change',
      'language':       'Language',
      'addPlaylist':    'Add Playlist',
      'settings':       'Settings',
      'about':          'About',
      'deviceInfo':     'Device Info',
      'home':           'Home',
      'favorites':      'Favorites',
      'search':         'Search',
      'exit':           'Exit',
      'channels':       'channels',
      'films':          'films',
      'shows':          'shows',
      'radioStations':  'Radio stations',
      'selectChannel':  'Select a channel',
      'noChannels':     'No channels',
      'searchHint':     'Search…',
      'searchMovies':   'Search movies…',
      'searchSeries':   'Search series…',
      'searchRadios':   'Search radios…',
      'loading':        'Loading…',
      'error':          'Error',
      'retry':          'Retry',
      'cancel':         'Cancel',
      'noContent':      'No content found',
      'noSeries':       'No series found',
      'selectPlaylist': 'Select Playlist',
      'aboutApp':       'About App',
      'playlistInfo':   'Playlist Info',
      'tapToLoad':      'Tap to load',
      'loadingLive':    'Loading live channels…',
      'loadingMovies':  'Loading movies…',
      'loadingSeries':  'Loading series…',
      'loadingMoment':  'This may take a moment for large servers',
      'noEpisodes':     'No episodes',
      'season':         'Season',
      'changeLanguage': 'Change Language',
      'addPlaylistHint':'Add M3U URL or Xtream Codes to start watching',
      'playlist':       'Playlist',
      'info':           'Info',
      'tvPrograms':     'TV Programs',
      'streamError':    'Stream error',
      'seasons':        'Seasons',
      'episodes':       'Episodes',
    },

    // ── Arabic ────────────────────────────────────────────────────────────────
    'ar': {
      'liveTV':         'قنوات مباشرة',
      'movies':         'أفلام',
      'series':         'مسلسلات',
      'radios':         'راديو',
      'refresh':        'تحديث',
      'change':         'تغيير',
      'language':       'اللغة',
      'addPlaylist':    'إضافة قائمة',
      'settings':       'الإعدادات',
      'about':          'حول',
      'deviceInfo':     'معلومات الجهاز',
      'home':           'الرئيسية',
      'favorites':      'المفضلة',
      'search':         'بحث',
      'exit':           'خروج',
      'channels':       'قنوات',
      'films':          'أفلام',
      'shows':          'مسلسلات',
      'radioStations':  'محطات الراديو',
      'selectChannel':  'اختر قناة',
      'noChannels':     'لا توجد قنوات',
      'searchHint':     'بحث…',
      'searchMovies':   'بحث في الأفلام…',
      'searchSeries':   'بحث في المسلسلات…',
      'searchRadios':   'بحث في الراديو…',
      'loading':        'جارٍ التحميل…',
      'error':          'خطأ',
      'retry':          'إعادة المحاولة',
      'cancel':         'إلغاء',
      'noContent':      'لا يوجد محتوى',
      'noSeries':       'لا توجد مسلسلات',
      'selectPlaylist': 'اختر قائمة',
      'aboutApp':       'حول التطبيق',
      'playlistInfo':   'معلومات القائمة',
      'tapToLoad':      'اضغط للتحميل',
      'loadingLive':    'جارٍ تحميل القنوات المباشرة…',
      'loadingMovies':  'جارٍ تحميل الأفلام…',
      'loadingSeries':  'جارٍ تحميل المسلسلات…',
      'loadingMoment':  'قد يستغرق هذا لحظة للخوادم الكبيرة',
      'noEpisodes':     'لا توجد حلقات',
      'season':         'موسم',
      'changeLanguage': 'تغيير اللغة',
      'addPlaylistHint':'أضف رابط M3U أو رموز Xtream للبدء',
      'playlist':       'قائمة',
      'info':           'معلومات',
      'tvPrograms':     'برامج التلفزيون',
      'streamError':    'خطأ في البث',
      'seasons':        'مواسم',
      'episodes':       'حلقات',
    },

    // ── French ────────────────────────────────────────────────────────────────
    'fr': {
      'liveTV':         'TV en direct',
      'movies':         'Films',
      'series':         'Séries',
      'radios':         'Radios',
      'refresh':        'Actualiser',
      'change':         'Changer',
      'language':       'Langue',
      'addPlaylist':    'Ajouter une liste',
      'settings':       'Paramètres',
      'about':          'À propos',
      'deviceInfo':     'Info appareil',
      'home':           'Accueil',
      'favorites':      'Favoris',
      'search':         'Recherche',
      'exit':           'Quitter',
      'channels':       'chaînes',
      'films':          'films',
      'shows':          'séries',
      'radioStations':  'Stations radio',
      'selectChannel':  'Sélectionner une chaîne',
      'noChannels':     'Aucune chaîne',
      'searchHint':     'Rechercher…',
      'searchMovies':   'Rechercher des films…',
      'searchSeries':   'Rechercher des séries…',
      'searchRadios':   'Rechercher des radios…',
      'loading':        'Chargement…',
      'error':          'Erreur',
      'retry':          'Réessayer',
      'cancel':         'Annuler',
      'noContent':      'Aucun contenu trouvé',
      'noSeries':       'Aucune série trouvée',
      'selectPlaylist': 'Sélectionner une liste',
      'aboutApp':       'À propos de l\'app',
      'playlistInfo':   'Infos liste',
      'tapToLoad':      'Appuyer pour charger',
      'loadingLive':    'Chargement des chaînes en direct…',
      'loadingMovies':  'Chargement des films…',
      'loadingSeries':  'Chargement des séries…',
      'loadingMoment':  'Cela peut prendre un moment pour les grands serveurs',
      'noEpisodes':     'Aucun épisode',
      'season':         'Saison',
      'changeLanguage': 'Changer la langue',
      'addPlaylistHint':'Ajoutez une URL M3U ou des codes Xtream pour commencer',
      'playlist':       'Liste de lecture',
      'info':           'Info',
      'tvPrograms':     'Programmes TV',
      'streamError':    'Erreur de flux',
      'seasons':        'Saisons',
      'episodes':       'Épisodes',
    },

    // ── Spanish ───────────────────────────────────────────────────────────────
    'es': {
      'liveTV':         'TV en vivo',
      'movies':         'Películas',
      'series':         'Series',
      'radios':         'Radios',
      'refresh':        'Actualizar',
      'change':         'Cambiar',
      'language':       'Idioma',
      'addPlaylist':    'Agregar lista',
      'settings':       'Ajustes',
      'about':          'Acerca de',
      'deviceInfo':     'Info del dispositivo',
      'home':           'Inicio',
      'favorites':      'Favoritos',
      'search':         'Buscar',
      'exit':           'Salir',
      'channels':       'canales',
      'films':          'películas',
      'shows':          'series',
      'radioStations':  'Estaciones de radio',
      'selectChannel':  'Seleccionar canal',
      'noChannels':     'Sin canales',
      'searchHint':     'Buscar…',
      'searchMovies':   'Buscar películas…',
      'searchSeries':   'Buscar series…',
      'searchRadios':   'Buscar radios…',
      'loading':        'Cargando…',
      'error':          'Error',
      'retry':          'Reintentar',
      'cancel':         'Cancelar',
      'noContent':      'Sin contenido encontrado',
      'noSeries':       'Sin series encontradas',
      'selectPlaylist': 'Seleccionar lista',
      'aboutApp':       'Acerca de la app',
      'playlistInfo':   'Info de lista',
      'tapToLoad':      'Toca para cargar',
      'loadingLive':    'Cargando canales en vivo…',
      'loadingMovies':  'Cargando películas…',
      'loadingSeries':  'Cargando series…',
      'loadingMoment':  'Esto puede tardar un momento en servidores grandes',
      'noEpisodes':     'Sin episodios',
      'season':         'Temporada',
      'changeLanguage': 'Cambiar idioma',
      'addPlaylistHint':'Añade URL M3U o códigos Xtream para empezar',
      'playlist':       'Lista de reproducción',
      'info':           'Info',
      'tvPrograms':     'Programas de TV',
      'streamError':    'Error de stream',
      'seasons':        'Temporadas',
      'episodes':       'Episodios',
    },

    // ── German ────────────────────────────────────────────────────────────────
    'de': {
      'liveTV':         'Live TV',
      'movies':         'Filme',
      'series':         'Serien',
      'radios':         'Radio',
      'refresh':        'Aktualisieren',
      'change':         'Wechseln',
      'language':       'Sprache',
      'addPlaylist':    'Playlist hinzufügen',
      'settings':       'Einstellungen',
      'about':          'Über',
      'deviceInfo':     'Gerätinfo',
      'home':           'Startseite',
      'favorites':      'Favoriten',
      'search':         'Suche',
      'exit':           'Beenden',
      'channels':       'Kanäle',
      'films':          'Filme',
      'shows':          'Serien',
      'radioStations':  'Radiosender',
      'selectChannel':  'Kanal auswählen',
      'noChannels':     'Keine Kanäle',
      'searchHint':     'Suchen…',
      'searchMovies':   'Filme suchen…',
      'searchSeries':   'Serien suchen…',
      'searchRadios':   'Radio suchen…',
      'loading':        'Laden…',
      'error':          'Fehler',
      'retry':          'Wiederholen',
      'cancel':         'Abbrechen',
      'noContent':      'Kein Inhalt gefunden',
      'noSeries':       'Keine Serien gefunden',
      'selectPlaylist': 'Playlist auswählen',
      'aboutApp':       'Über die App',
      'playlistInfo':   'Playlist-Info',
      'tapToLoad':      'Tippen zum Laden',
      'loadingLive':    'Live-Kanäle werden geladen…',
      'loadingMovies':  'Filme werden geladen…',
      'loadingSeries':  'Serien werden geladen…',
      'loadingMoment':  'Dies kann bei großen Servern einen Moment dauern',
      'noEpisodes':     'Keine Episoden',
      'season':         'Staffel',
      'changeLanguage': 'Sprache ändern',
      'addPlaylistHint':'M3U-URL oder Xtream Codes hinzufügen',
      'playlist':       'Wiedergabeliste',
      'info':           'Info',
      'tvPrograms':     'TV-Programme',
      'streamError':    'Stream-Fehler',
      'seasons':        'Staffeln',
      'episodes':       'Episoden',
    },

    // ── Turkish ───────────────────────────────────────────────────────────────
    'tr': {
      'liveTV':         'Canlı TV',
      'movies':         'Filmler',
      'series':         'Diziler',
      'radios':         'Radyo',
      'refresh':        'Yenile',
      'change':         'Değiştir',
      'language':       'Dil',
      'addPlaylist':    'Liste Ekle',
      'settings':       'Ayarlar',
      'about':          'Hakkında',
      'deviceInfo':     'Cihaz Bilgisi',
      'home':           'Ana Sayfa',
      'favorites':      'Favoriler',
      'search':         'Ara',
      'exit':           'Çıkış',
      'channels':       'kanal',
      'films':          'film',
      'shows':          'dizi',
      'radioStations':  'Radyo istasyonları',
      'selectChannel':  'Kanal seç',
      'noChannels':     'Kanal yok',
      'searchHint':     'Ara…',
      'searchMovies':   'Film ara…',
      'searchSeries':   'Dizi ara…',
      'searchRadios':   'Radyo ara…',
      'loading':        'Yükleniyor…',
      'error':          'Hata',
      'retry':          'Tekrar Dene',
      'cancel':         'İptal',
      'noContent':      'İçerik bulunamadı',
      'noSeries':       'Dizi bulunamadı',
      'selectPlaylist': 'Liste Seç',
      'aboutApp':       'Uygulama Hakkında',
      'playlistInfo':   'Liste Bilgisi',
      'tapToLoad':      'Yüklemek için tıklayın',
      'loadingLive':    'Canlı kanallar yükleniyor…',
      'loadingMovies':  'Filmler yükleniyor…',
      'loadingSeries':  'Diziler yükleniyor…',
      'loadingMoment':  'Büyük sunucular için bu biraz sürebilir',
      'noEpisodes':     'Bölüm yok',
      'season':         'Sezon',
      'changeLanguage': 'Dil Değiştir',
      'addPlaylistHint':'İzlemeye başlamak için M3U URL veya Xtream Kodları ekleyin',
      'playlist':       'Oynatma listesi',
      'info':           'Bilgi',
      'tvPrograms':     'TV Programları',
      'streamError':    'Yayın hatası',
      'seasons':        'Sezonlar',
      'episodes':       'Bölümler',
    },

    // ── Italian ───────────────────────────────────────────────────────────────
    'it': {
      'liveTV':         'TV in diretta',
      'movies':         'Film',
      'series':         'Serie',
      'radios':         'Radio',
      'refresh':        'Aggiorna',
      'change':         'Cambia',
      'language':       'Lingua',
      'addPlaylist':    'Aggiungi playlist',
      'settings':       'Impostazioni',
      'about':          'Informazioni',
      'deviceInfo':     'Info dispositivo',
      'home':           'Home',
      'favorites':      'Preferiti',
      'search':         'Cerca',
      'exit':           'Esci',
      'channels':       'canali',
      'films':          'film',
      'shows':          'serie',
      'radioStations':  'Stazioni radio',
      'selectChannel':  'Seleziona un canale',
      'noChannels':     'Nessun canale',
      'searchHint':     'Cerca…',
      'searchMovies':   'Cerca film…',
      'searchSeries':   'Cerca serie…',
      'searchRadios':   'Cerca radio…',
      'loading':        'Caricamento…',
      'error':          'Errore',
      'retry':          'Riprova',
      'cancel':         'Annulla',
      'noContent':      'Nessun contenuto trovato',
      'noSeries':       'Nessuna serie trovata',
      'selectPlaylist': 'Seleziona playlist',
      'aboutApp':       'Info sull\'app',
      'playlistInfo':   'Info playlist',
      'tapToLoad':      'Tocca per caricare',
      'loadingLive':    'Caricamento canali in diretta…',
      'loadingMovies':  'Caricamento film…',
      'loadingSeries':  'Caricamento serie…',
      'loadingMoment':  'Potrebbe richiedere un momento per server grandi',
      'noEpisodes':     'Nessun episodio',
      'season':         'Stagione',
      'changeLanguage': 'Cambia lingua',
      'addPlaylistHint':'Aggiungi URL M3U o codici Xtream per iniziare',
      'playlist':       'Playlist',
      'info':           'Info',
      'tvPrograms':     'Programmi TV',
      'streamError':    'Errore stream',
      'seasons':        'Stagioni',
      'episodes':       'Episodi',
    },

    // ── Dutch ─────────────────────────────────────────────────────────────────
    'nl': {
      'liveTV':         'Live TV',
      'movies':         'Films',
      'series':         'Series',
      'radios':         'Radio',
      'refresh':        'Vernieuwen',
      'change':         'Wijzigen',
      'language':       'Taal',
      'addPlaylist':    'Afspeellijst toevoegen',
      'settings':       'Instellingen',
      'about':          'Over',
      'deviceInfo':     'Apparaatinfo',
      'home':           'Home',
      'favorites':      'Favorieten',
      'search':         'Zoeken',
      'exit':           'Afsluiten',
      'channels':       'kanalen',
      'films':          'films',
      'shows':          'series',
      'radioStations':  'Radiostations',
      'selectChannel':  'Selecteer een kanaal',
      'noChannels':     'Geen kanalen',
      'searchHint':     'Zoeken…',
      'searchMovies':   'Films zoeken…',
      'searchSeries':   'Series zoeken…',
      'searchRadios':   'Radio zoeken…',
      'loading':        'Laden…',
      'error':          'Fout',
      'retry':          'Opnieuw proberen',
      'cancel':         'Annuleren',
      'noContent':      'Geen inhoud gevonden',
      'noSeries':       'Geen series gevonden',
      'selectPlaylist': 'Selecteer afspeellijst',
      'aboutApp':       'Over de app',
      'playlistInfo':   'Afspeellijstinfo',
      'tapToLoad':      'Tik om te laden',
      'loadingLive':    'Live kanalen laden…',
      'loadingMovies':  'Films laden…',
      'loadingSeries':  'Series laden…',
      'loadingMoment':  'Dit kan even duren voor grote servers',
      'noEpisodes':     'Geen afleveringen',
      'season':         'Seizoen',
      'changeLanguage': 'Taal wijzigen',
      'addPlaylistHint':'Voeg een M3U URL of Xtream Codes toe om te beginnen',
      'playlist':       'Afspeellijst',
      'info':           'Info',
      'tvPrograms':     'TV-programma\'s',
      'streamError':    'Streamfout',
      'seasons':        'Seizoenen',
      'episodes':       'Afleveringen',
    },

    // ── Portuguese ────────────────────────────────────────────────────────────
    'pt': {
      'liveTV':         'TV ao vivo',
      'movies':         'Filmes',
      'series':         'Séries',
      'radios':         'Rádio',
      'refresh':        'Atualizar',
      'change':         'Alterar',
      'language':       'Idioma',
      'addPlaylist':    'Adicionar lista',
      'settings':       'Configurações',
      'about':          'Sobre',
      'deviceInfo':     'Info do dispositivo',
      'home':           'Início',
      'favorites':      'Favoritos',
      'search':         'Pesquisar',
      'exit':           'Sair',
      'channels':       'canais',
      'films':          'filmes',
      'shows':          'séries',
      'radioStations':  'Estações de rádio',
      'selectChannel':  'Selecionar canal',
      'noChannels':     'Sem canais',
      'searchHint':     'Pesquisar…',
      'searchMovies':   'Pesquisar filmes…',
      'searchSeries':   'Pesquisar séries…',
      'searchRadios':   'Pesquisar rádios…',
      'loading':        'Carregando…',
      'error':          'Erro',
      'retry':          'Tentar novamente',
      'cancel':         'Cancelar',
      'noContent':      'Nenhum conteúdo encontrado',
      'noSeries':       'Nenhuma série encontrada',
      'selectPlaylist': 'Selecionar lista',
      'aboutApp':       'Sobre o app',
      'playlistInfo':   'Info da lista',
      'tapToLoad':      'Toque para carregar',
      'loadingLive':    'Carregando canais ao vivo…',
      'loadingMovies':  'Carregando filmes…',
      'loadingSeries':  'Carregando séries…',
      'loadingMoment':  'Isso pode levar um momento para servidores grandes',
      'noEpisodes':     'Nenhum episódio',
      'season':         'Temporada',
      'changeLanguage': 'Alterar idioma',
      'addPlaylistHint':'Adicione uma URL M3U ou códigos Xtream para começar',
      'playlist':       'Lista de reprodução',
      'info':           'Info',
      'tvPrograms':     'Programas de TV',
      'streamError':    'Erro de stream',
      'seasons':        'Temporadas',
      'episodes':       'Episódios',
    },

    // ── Russian ───────────────────────────────────────────────────────────────
    'ru': {
      'liveTV':         'Прямой эфир',
      'movies':         'Фильмы',
      'series':         'Сериалы',
      'radios':         'Радио',
      'refresh':        'Обновить',
      'change':         'Изменить',
      'language':       'Язык',
      'addPlaylist':    'Добавить плейлист',
      'settings':       'Настройки',
      'about':          'О приложении',
      'deviceInfo':     'Инфо об устройстве',
      'home':           'Главная',
      'favorites':      'Избранное',
      'search':         'Поиск',
      'exit':           'Выход',
      'channels':       'каналов',
      'films':          'фильмов',
      'shows':          'сериалов',
      'radioStations':  'Радиостанции',
      'selectChannel':  'Выбрать канал',
      'noChannels':     'Нет каналов',
      'searchHint':     'Поиск…',
      'searchMovies':   'Поиск фильмов…',
      'searchSeries':   'Поиск сериалов…',
      'searchRadios':   'Поиск радио…',
      'loading':        'Загрузка…',
      'error':          'Ошибка',
      'retry':          'Повторить',
      'cancel':         'Отмена',
      'noContent':      'Контент не найден',
      'noSeries':       'Сериалы не найдены',
      'selectPlaylist': 'Выбрать плейлист',
      'aboutApp':       'О приложении',
      'playlistInfo':   'Инфо плейлиста',
      'tapToLoad':      'Нажмите для загрузки',
      'loadingLive':    'Загрузка прямых каналов…',
      'loadingMovies':  'Загрузка фильмов…',
      'loadingSeries':  'Загрузка сериалов…',
      'loadingMoment':  'Для больших серверов это может занять время',
      'noEpisodes':     'Нет эпизодов',
      'season':         'Сезон',
      'changeLanguage': 'Сменить язык',
      'addPlaylistHint':'Добавьте M3U URL или коды Xtream для начала',
      'playlist':       'Плейлист',
      'info':           'Инфо',
      'tvPrograms':     'ТВ-программа',
      'streamError':    'Ошибка потока',
      'seasons':        'Сезоны',
      'episodes':       'Эпизоды',
    },

    // ── Chinese ───────────────────────────────────────────────────────────────
    'zh': {
      'liveTV':         '直播电视',
      'movies':         '电影',
      'series':         '剧集',
      'radios':         '广播',
      'refresh':        '刷新',
      'change':         '更改',
      'language':       '语言',
      'addPlaylist':    '添加播放列表',
      'settings':       '设置',
      'about':          '关于',
      'deviceInfo':     '设备信息',
      'home':           '首页',
      'favorites':      '收藏',
      'search':         '搜索',
      'exit':           '退出',
      'channels':       '频道',
      'films':          '电影',
      'shows':          '剧集',
      'radioStations':  '广播电台',
      'selectChannel':  '选择频道',
      'noChannels':     '没有频道',
      'searchHint':     '搜索…',
      'searchMovies':   '搜索电影…',
      'searchSeries':   '搜索剧集…',
      'searchRadios':   '搜索广播…',
      'loading':        '加载中…',
      'error':          '错误',
      'retry':          '重试',
      'cancel':         '取消',
      'noContent':      '未找到内容',
      'noSeries':       '未找到剧集',
      'selectPlaylist': '选择播放列表',
      'aboutApp':       '关于应用',
      'playlistInfo':   '播放列表信息',
      'tapToLoad':      '点击加载',
      'loadingLive':    '正在加载直播频道…',
      'loadingMovies':  '正在加载电影…',
      'loadingSeries':  '正在加载剧集…',
      'loadingMoment':  '大型服务器可能需要一点时间',
      'noEpisodes':     '没有剧集',
      'season':         '季',
      'changeLanguage': '更改语言',
      'addPlaylistHint':'添加M3U链接或Xtream代码开始观看',
      'playlist':       '播放列表',
      'info':           '信息',
      'tvPrograms':     '电视节目',
      'streamError':    '流错误',
      'seasons':        '季',
      'episodes':       '集',
    },

    // ── Japanese ──────────────────────────────────────────────────────────────
    'ja': {
      'liveTV':         'ライブTV',
      'movies':         '映画',
      'series':         'シリーズ',
      'radios':         'ラジオ',
      'refresh':        '更新',
      'change':         '変更',
      'language':       '言語',
      'addPlaylist':    'プレイリスト追加',
      'settings':       '設定',
      'about':          'について',
      'deviceInfo':     'デバイス情報',
      'home':           'ホーム',
      'favorites':      'お気に入り',
      'search':         '検索',
      'exit':           '終了',
      'channels':       'チャンネル',
      'films':          '映画',
      'shows':          'シリーズ',
      'radioStations':  'ラジオ局',
      'selectChannel':  'チャンネルを選択',
      'noChannels':     'チャンネルなし',
      'searchHint':     '検索…',
      'searchMovies':   '映画を検索…',
      'searchSeries':   'シリーズを検索…',
      'searchRadios':   'ラジオを検索…',
      'loading':        '読み込み中…',
      'error':          'エラー',
      'retry':          '再試行',
      'cancel':         'キャンセル',
      'noContent':      'コンテンツが見つかりません',
      'noSeries':       'シリーズが見つかりません',
      'selectPlaylist': 'プレイリストを選択',
      'aboutApp':       'アプリについて',
      'playlistInfo':   'プレイリスト情報',
      'tapToLoad':      'タップして読み込む',
      'loadingLive':    'ライブチャンネルを読み込み中…',
      'loadingMovies':  '映画を読み込み中…',
      'loadingSeries':  'シリーズを読み込み中…',
      'loadingMoment':  '大きなサーバーには時間がかかる場合があります',
      'noEpisodes':     'エピソードなし',
      'season':         'シーズン',
      'changeLanguage': '言語を変更',
      'addPlaylistHint':'M3U URLまたはXtreamコードを追加して視聴開始',
      'playlist':       'プレイリスト',
      'info':           '情報',
      'tvPrograms':     'TVプログラム',
      'streamError':    'ストリームエラー',
      'seasons':        'シーズン',
      'episodes':       'エピソード',
    },

    // ── Korean ────────────────────────────────────────────────────────────────
    'ko': {
      'liveTV':         '실시간 TV',
      'movies':         '영화',
      'series':         '시리즈',
      'radios':         '라디오',
      'refresh':        '새로고침',
      'change':         '변경',
      'language':       '언어',
      'addPlaylist':    '재생목록 추가',
      'settings':       '설정',
      'about':          '정보',
      'deviceInfo':     '기기 정보',
      'home':           '홈',
      'favorites':      '즐겨찾기',
      'search':         '검색',
      'exit':           '종료',
      'channels':       '채널',
      'films':          '영화',
      'shows':          '시리즈',
      'radioStations':  '라디오 방송국',
      'selectChannel':  '채널 선택',
      'noChannels':     '채널 없음',
      'searchHint':     '검색…',
      'searchMovies':   '영화 검색…',
      'searchSeries':   '시리즈 검색…',
      'searchRadios':   '라디오 검색…',
      'loading':        '로딩 중…',
      'error':          '오류',
      'retry':          '재시도',
      'cancel':         '취소',
      'noContent':      '콘텐츠를 찾을 수 없습니다',
      'noSeries':       '시리즈를 찾을 수 없습니다',
      'selectPlaylist': '재생목록 선택',
      'aboutApp':       '앱 정보',
      'playlistInfo':   '재생목록 정보',
      'tapToLoad':      '탭하여 로드',
      'loadingLive':    '실시간 채널 로딩 중…',
      'loadingMovies':  '영화 로딩 중…',
      'loadingSeries':  '시리즈 로딩 중…',
      'loadingMoment':  '대형 서버의 경우 잠시 시간이 걸릴 수 있습니다',
      'noEpisodes':     '에피소드 없음',
      'season':         '시즌',
      'changeLanguage': '언어 변경',
      'addPlaylistHint':'M3U URL 또는 Xtream 코드를 추가하여 시청 시작',
      'playlist':       '재생목록',
      'info':           '정보',
      'tvPrograms':     'TV 프로그램',
      'streamError':    '스트림 오류',
      'seasons':        '시즌',
      'episodes':       '에피소드',
    },

    // ── Persian ───────────────────────────────────────────────────────────────
    'fa': {
      'liveTV':         'تلویزیون زنده',
      'movies':         'فیلم‌ها',
      'series':         'سریال‌ها',
      'radios':         'رادیو',
      'refresh':        'بارگذاری مجدد',
      'change':         'تغییر',
      'language':       'زبان',
      'addPlaylist':    'افزودن لیست پخش',
      'settings':       'تنظیمات',
      'about':          'درباره',
      'deviceInfo':     'اطلاعات دستگاه',
      'home':           'خانه',
      'favorites':      'علاقه‌مندی‌ها',
      'search':         'جستجو',
      'exit':           'خروج',
      'channels':       'کانال',
      'films':          'فیلم',
      'shows':          'سریال',
      'radioStations':  'ایستگاه‌های رادیویی',
      'selectChannel':  'کانال را انتخاب کنید',
      'noChannels':     'کانالی وجود ندارد',
      'searchHint':     'جستجو…',
      'searchMovies':   'جستجوی فیلم…',
      'searchSeries':   'جستجوی سریال…',
      'searchRadios':   'جستجوی رادیو…',
      'loading':        'در حال بارگذاری…',
      'error':          'خطا',
      'retry':          'تلاش مجدد',
      'cancel':         'لغو',
      'noContent':      'محتوایی یافت نشد',
      'noSeries':       'سریالی یافت نشد',
      'selectPlaylist': 'لیست پخش را انتخاب کنید',
      'aboutApp':       'درباره برنامه',
      'playlistInfo':   'اطلاعات لیست پخش',
      'tapToLoad':      'برای بارگذاری ضربه بزنید',
      'loadingLive':    'در حال بارگذاری کانال‌های زنده…',
      'loadingMovies':  'در حال بارگذاری فیلم‌ها…',
      'loadingSeries':  'در حال بارگذاری سریال‌ها…',
      'loadingMoment':  'برای سرورهای بزرگ ممکن است کمی طول بکشد',
      'noEpisodes':     'قسمتی وجود ندارد',
      'season':         'فصل',
      'changeLanguage': 'تغییر زبان',
      'addPlaylistHint':'برای شروع تماشا، URL M3U یا کدهای Xtream اضافه کنید',
      'playlist':       'لیست پخش',
      'info':           'اطلاعات',
      'tvPrograms':     'برنامه‌های تلویزیونی',
      'streamError':    'خطای پخش',
      'seasons':        'فصل‌ها',
      'episodes':       'قسمت‌ها',
    },

    // ── Polish ────────────────────────────────────────────────────────────────
    'pl': {
      'liveTV':         'TV na żywo',
      'movies':         'Filmy',
      'series':         'Seriale',
      'radios':         'Radio',
      'refresh':        'Odśwież',
      'change':         'Zmień',
      'language':       'Język',
      'addPlaylist':    'Dodaj playlistę',
      'settings':       'Ustawienia',
      'about':          'O aplikacji',
      'deviceInfo':     'Info o urządzeniu',
      'home':           'Strona główna',
      'favorites':      'Ulubione',
      'search':         'Szukaj',
      'exit':           'Wyjdź',
      'channels':       'kanałów',
      'films':          'filmów',
      'shows':          'seriali',
      'radioStations':  'Stacje radiowe',
      'selectChannel':  'Wybierz kanał',
      'noChannels':     'Brak kanałów',
      'searchHint':     'Szukaj…',
      'searchMovies':   'Szukaj filmów…',
      'searchSeries':   'Szukaj seriali…',
      'searchRadios':   'Szukaj radia…',
      'loading':        'Ładowanie…',
      'error':          'Błąd',
      'retry':          'Spróbuj ponownie',
      'cancel':         'Anuluj',
      'noContent':      'Nie znaleziono treści',
      'noSeries':       'Nie znaleziono seriali',
      'selectPlaylist': 'Wybierz playlistę',
      'aboutApp':       'O aplikacji',
      'playlistInfo':   'Info playlisty',
      'tapToLoad':      'Dotknij, aby załadować',
      'loadingLive':    'Ładowanie kanałów na żywo…',
      'loadingMovies':  'Ładowanie filmów…',
      'loadingSeries':  'Ładowanie seriali…',
      'loadingMoment':  'Może to chwilę potrwać dla dużych serwerów',
      'noEpisodes':     'Brak odcinków',
      'season':         'Sezon',
      'changeLanguage': 'Zmień język',
      'addPlaylistHint':'Dodaj URL M3U lub kody Xtream, aby rozpocząć oglądanie',
      'playlist':       'Playlista',
      'info':           'Info',
      'tvPrograms':     'Programy TV',
      'streamError':    'Błąd strumienia',
      'seasons':        'Sezony',
      'episodes':       'Odcinki',
    },

    // ── Romanian ──────────────────────────────────────────────────────────────
    'ro': {
      'liveTV':         'TV Live',
      'movies':         'Filme',
      'series':         'Seriale',
      'radios':         'Radio',
      'refresh':        'Reîncarcă',
      'change':         'Schimbă',
      'language':       'Limbă',
      'addPlaylist':    'Adaugă playlist',
      'settings':       'Setări',
      'about':          'Despre',
      'deviceInfo':     'Info dispozitiv',
      'home':           'Acasă',
      'favorites':      'Favorite',
      'search':         'Caută',
      'exit':           'Ieșire',
      'channels':       'canale',
      'films':          'filme',
      'shows':          'seriale',
      'radioStations':  'Stații radio',
      'selectChannel':  'Selectați un canal',
      'noChannels':     'Niciun canal',
      'searchHint':     'Caută…',
      'searchMovies':   'Caută filme…',
      'searchSeries':   'Caută seriale…',
      'searchRadios':   'Caută radio…',
      'loading':        'Se încarcă…',
      'error':          'Eroare',
      'retry':          'Reîncearcă',
      'cancel':         'Anulează',
      'noContent':      'Niciun conținut găsit',
      'noSeries':       'Niciun serial găsit',
      'selectPlaylist': 'Selectați playlist',
      'aboutApp':       'Despre aplicație',
      'playlistInfo':   'Info playlist',
      'tapToLoad':      'Atinge pentru a încărca',
      'loadingLive':    'Se încarcă canalele live…',
      'loadingMovies':  'Se încarcă filmele…',
      'loadingSeries':  'Se încarcă serialele…',
      'loadingMoment':  'Poate dura un moment pentru servere mari',
      'noEpisodes':     'Niciun episod',
      'season':         'Sezon',
      'changeLanguage': 'Schimbă limba',
      'addPlaylistHint':'Adaugă URL M3U sau coduri Xtream pentru a începe',
      'playlist':       'Playlist',
      'info':           'Info',
      'tvPrograms':     'Programe TV',
      'streamError':    'Eroare stream',
      'seasons':        'Sezoane',
      'episodes':       'Episoade',
    },

    // ── Greek ─────────────────────────────────────────────────────────────────
    'el': {
      'liveTV':         'Ζωντανή TV',
      'movies':         'Ταινίες',
      'series':         'Σειρές',
      'radios':         'Ραδιόφωνο',
      'refresh':        'Ανανέωση',
      'change':         'Αλλαγή',
      'language':       'Γλώσσα',
      'addPlaylist':    'Προσθήκη λίστας',
      'settings':       'Ρυθμίσεις',
      'about':          'Σχετικά',
      'deviceInfo':     'Πληροφορίες συσκευής',
      'home':           'Αρχική',
      'favorites':      'Αγαπημένα',
      'search':         'Αναζήτηση',
      'exit':           'Έξοδος',
      'channels':       'κανάλια',
      'films':          'ταινίες',
      'shows':          'σειρές',
      'radioStations':  'Ραδιοφωνικοί σταθμοί',
      'selectChannel':  'Επιλογή καναλιού',
      'noChannels':     'Χωρίς κανάλια',
      'searchHint':     'Αναζήτηση…',
      'searchMovies':   'Αναζήτηση ταινιών…',
      'searchSeries':   'Αναζήτηση σειρών…',
      'searchRadios':   'Αναζήτηση ραδιοφώνου…',
      'loading':        'Φόρτωση…',
      'error':          'Σφάλμα',
      'retry':          'Επανάληψη',
      'cancel':         'Ακύρωση',
      'noContent':      'Δεν βρέθηκε περιεχόμενο',
      'noSeries':       'Δεν βρέθηκαν σειρές',
      'selectPlaylist': 'Επιλογή λίστας',
      'aboutApp':       'Σχετικά με την εφαρμογή',
      'playlistInfo':   'Πληροφορίες λίστας',
      'tapToLoad':      'Πατήστε για φόρτωση',
      'loadingLive':    'Φόρτωση ζωντανών καναλιών…',
      'loadingMovies':  'Φόρτωση ταινιών…',
      'loadingSeries':  'Φόρτωση σειρών…',
      'loadingMoment':  'Μπορεί να χρειαστεί λίγο χρόνο για μεγάλους διακομιστές',
      'noEpisodes':     'Χωρίς επεισόδια',
      'season':         'Σεζόν',
      'changeLanguage': 'Αλλαγή γλώσσας',
      'addPlaylistHint':'Προσθέστε URL M3U ή κωδικούς Xtream για να ξεκινήσετε',
      'playlist':       'Λίστα αναπαραγωγής',
      'info':           'Πληροφορίες',
      'tvPrograms':     'Τηλεοπτικά προγράμματα',
      'streamError':    'Σφάλμα ροής',
      'seasons':        'Σεζόν',
      'episodes':       'Επεισόδια',
    },

    // ── Ukrainian ─────────────────────────────────────────────────────────────
    'uk': {
      'liveTV':         'Прямий ефір',
      'movies':         'Фільми',
      'series':         'Серіали',
      'radios':         'Радіо',
      'refresh':        'Оновити',
      'change':         'Змінити',
      'language':       'Мова',
      'addPlaylist':    'Додати плейлист',
      'settings':       'Налаштування',
      'about':          'Про застосунок',
      'deviceInfo':     'Інфо про пристрій',
      'home':           'Головна',
      'favorites':      'Вибране',
      'search':         'Пошук',
      'exit':           'Вихід',
      'channels':       'каналів',
      'films':          'фільмів',
      'shows':          'серіалів',
      'radioStations':  'Радіостанції',
      'selectChannel':  'Вибрати канал',
      'noChannels':     'Немає каналів',
      'searchHint':     'Пошук…',
      'searchMovies':   'Пошук фільмів…',
      'searchSeries':   'Пошук серіалів…',
      'searchRadios':   'Пошук радіо…',
      'loading':        'Завантаження…',
      'error':          'Помилка',
      'retry':          'Повторити',
      'cancel':         'Скасувати',
      'noContent':      'Вміст не знайдено',
      'noSeries':       'Серіали не знайдено',
      'selectPlaylist': 'Вибрати плейлист',
      'aboutApp':       'Про застосунок',
      'playlistInfo':   'Інфо плейлиста',
      'tapToLoad':      'Натисніть для завантаження',
      'loadingLive':    'Завантаження прямих каналів…',
      'loadingMovies':  'Завантаження фільмів…',
      'loadingSeries':  'Завантаження серіалів…',
      'loadingMoment':  'Для великих серверів це може зайняти час',
      'noEpisodes':     'Немає епізодів',
      'season':         'Сезон',
      'changeLanguage': 'Змінити мову',
      'addPlaylistHint':'Додайте M3U URL або коди Xtream для початку перегляду',
      'playlist':       'Плейлист',
      'info':           'Інфо',
      'tvPrograms':     'ТВ-програма',
      'streamError':    'Помилка потоку',
      'seasons':        'Сезони',
      'episodes':       'Епізоди',
    },

    // ── Swedish ───────────────────────────────────────────────────────────────
    'sv': {
      'liveTV':         'Live TV',
      'movies':         'Filmer',
      'series':         'Serier',
      'radios':         'Radio',
      'refresh':        'Uppdatera',
      'change':         'Ändra',
      'language':       'Språk',
      'addPlaylist':    'Lägg till spellista',
      'settings':       'Inställningar',
      'about':          'Om',
      'deviceInfo':     'Enhetsinformation',
      'home':           'Hem',
      'favorites':      'Favoriter',
      'search':         'Sök',
      'exit':           'Avsluta',
      'channels':       'kanaler',
      'films':          'filmer',
      'shows':          'serier',
      'radioStations':  'Radiostationer',
      'selectChannel':  'Välj kanal',
      'noChannels':     'Inga kanaler',
      'searchHint':     'Sök…',
      'searchMovies':   'Sök filmer…',
      'searchSeries':   'Sök serier…',
      'searchRadios':   'Sök radio…',
      'loading':        'Laddar…',
      'error':          'Fel',
      'retry':          'Försök igen',
      'cancel':         'Avbryt',
      'noContent':      'Inget innehåll hittades',
      'noSeries':       'Inga serier hittades',
      'selectPlaylist': 'Välj spellista',
      'aboutApp':       'Om appen',
      'playlistInfo':   'Spellistinfo',
      'tapToLoad':      'Tryck för att ladda',
      'loadingLive':    'Laddar live-kanaler…',
      'loadingMovies':  'Laddar filmer…',
      'loadingSeries':  'Laddar serier…',
      'loadingMoment':  'Det kan ta ett ögonblick för stora servrar',
      'noEpisodes':     'Inga avsnitt',
      'season':         'Säsong',
      'changeLanguage': 'Ändra språk',
      'addPlaylistHint':'Lägg till M3U-URL eller Xtream-koder för att börja titta',
      'playlist':       'Spellista',
      'info':           'Info',
      'tvPrograms':     'TV-program',
      'streamError':    'Strömningsfel',
      'seasons':        'Säsonger',
      'episodes':       'Avsnitt',
    },

    // ── Norwegian ─────────────────────────────────────────────────────────────
    'no': {
      'liveTV':         'Live TV',
      'movies':         'Filmer',
      'series':         'Serier',
      'radios':         'Radio',
      'refresh':        'Oppdater',
      'change':         'Endre',
      'language':       'Språk',
      'addPlaylist':    'Legg til spilleliste',
      'settings':       'Innstillinger',
      'about':          'Om',
      'deviceInfo':     'Enhetsinformasjon',
      'home':           'Hjem',
      'favorites':      'Favoritter',
      'search':         'Søk',
      'exit':           'Avslutt',
      'channels':       'kanaler',
      'films':          'filmer',
      'shows':          'serier',
      'radioStations':  'Radiostasjoner',
      'selectChannel':  'Velg kanal',
      'noChannels':     'Ingen kanaler',
      'searchHint':     'Søk…',
      'searchMovies':   'Søk filmer…',
      'searchSeries':   'Søk serier…',
      'searchRadios':   'Søk radio…',
      'loading':        'Laster…',
      'error':          'Feil',
      'retry':          'Prøv igjen',
      'cancel':         'Avbryt',
      'noContent':      'Ingen innhold funnet',
      'noSeries':       'Ingen serier funnet',
      'selectPlaylist': 'Velg spilleliste',
      'aboutApp':       'Om appen',
      'playlistInfo':   'Spillelisteinfo',
      'tapToLoad':      'Trykk for å laste',
      'loadingLive':    'Laster live-kanaler…',
      'loadingMovies':  'Laster filmer…',
      'loadingSeries':  'Laster serier…',
      'loadingMoment':  'Dette kan ta et øyeblikk for store servere',
      'noEpisodes':     'Ingen episoder',
      'season':         'Sesong',
      'changeLanguage': 'Endre språk',
      'addPlaylistHint':'Legg til M3U-URL eller Xtream-koder for å begynne å se',
      'playlist':       'Spilleliste',
      'info':           'Info',
      'tvPrograms':     'TV-programmer',
      'streamError':    'Strømmefeil',
      'seasons':        'Sesonger',
      'episodes':       'Episoder',
    },

    // ── Danish ────────────────────────────────────────────────────────────────
    'da': {
      'liveTV':         'Live TV',
      'movies':         'Film',
      'series':         'Serier',
      'radios':         'Radio',
      'refresh':        'Opdater',
      'change':         'Skift',
      'language':       'Sprog',
      'addPlaylist':    'Tilføj afspilningsliste',
      'settings':       'Indstillinger',
      'about':          'Om',
      'deviceInfo':     'Enhedsoplysninger',
      'home':           'Hjem',
      'favorites':      'Favoritter',
      'search':         'Søg',
      'exit':           'Afslut',
      'channels':       'kanaler',
      'films':          'film',
      'shows':          'serier',
      'radioStations':  'Radiostationer',
      'selectChannel':  'Vælg kanal',
      'noChannels':     'Ingen kanaler',
      'searchHint':     'Søg…',
      'searchMovies':   'Søg film…',
      'searchSeries':   'Søg serier…',
      'searchRadios':   'Søg radio…',
      'loading':        'Indlæser…',
      'error':          'Fejl',
      'retry':          'Prøv igen',
      'cancel':         'Annuller',
      'noContent':      'Intet indhold fundet',
      'noSeries':       'Ingen serier fundet',
      'selectPlaylist': 'Vælg afspilningsliste',
      'aboutApp':       'Om appen',
      'playlistInfo':   'Afspilningslisteinfo',
      'tapToLoad':      'Tryk for at indlæse',
      'loadingLive':    'Indlæser live-kanaler…',
      'loadingMovies':  'Indlæser film…',
      'loadingSeries':  'Indlæser serier…',
      'loadingMoment':  'Dette kan tage et øjeblik for store servere',
      'noEpisodes':     'Ingen episoder',
      'season':         'Sæson',
      'changeLanguage': 'Skift sprog',
      'addPlaylistHint':'Tilføj M3U URL eller Xtream-koder for at begynde at se',
      'playlist':       'Afspilningsliste',
      'info':           'Info',
      'tvPrograms':     'TV-programmer',
      'streamError':    'Streamingfejl',
      'seasons':        'Sæsoner',
      'episodes':       'Episoder',
    },

    // ── Finnish ───────────────────────────────────────────────────────────────
    'fi': {
      'liveTV':         'Live TV',
      'movies':         'Elokuvat',
      'series':         'Sarjat',
      'radios':         'Radio',
      'refresh':        'Päivitä',
      'change':         'Vaihda',
      'language':       'Kieli',
      'addPlaylist':    'Lisää soittolista',
      'settings':       'Asetukset',
      'about':          'Tietoja',
      'deviceInfo':     'Laitteen tiedot',
      'home':           'Koti',
      'favorites':      'Suosikit',
      'search':         'Etsi',
      'exit':           'Poistu',
      'channels':       'kanavaa',
      'films':          'elokuvaa',
      'shows':          'sarjaa',
      'radioStations':  'Radioasemat',
      'selectChannel':  'Valitse kanava',
      'noChannels':     'Ei kanavia',
      'searchHint':     'Etsi…',
      'searchMovies':   'Etsi elokuvia…',
      'searchSeries':   'Etsi sarjoja…',
      'searchRadios':   'Etsi radioasemia…',
      'loading':        'Ladataan…',
      'error':          'Virhe',
      'retry':          'Yritä uudelleen',
      'cancel':         'Peruuta',
      'noContent':      'Sisältöä ei löydy',
      'noSeries':       'Sarjoja ei löydy',
      'selectPlaylist': 'Valitse soittolista',
      'aboutApp':       'Tietoja sovelluksesta',
      'playlistInfo':   'Soittolistan tiedot',
      'tapToLoad':      'Napauta ladataksesi',
      'loadingLive':    'Ladataan live-kanavia…',
      'loadingMovies':  'Ladataan elokuvia…',
      'loadingSeries':  'Ladataan sarjoja…',
      'loadingMoment':  'Suurille palvelimille voi kulua hetki',
      'noEpisodes':     'Ei jaksoja',
      'season':         'Kausi',
      'changeLanguage': 'Vaihda kieli',
      'addPlaylistHint':'Lisää M3U URL tai Xtream-koodit aloittaaksesi katselun',
      'playlist':       'Soittolista',
      'info':           'Tiedot',
      'tvPrograms':     'TV-ohjelmat',
      'streamError':    'Virtausvirhe',
      'seasons':        'Kaudet',
      'episodes':       'Jaksot',
    },

    // ── Czech ─────────────────────────────────────────────────────────────────
    'cs': {
      'liveTV':         'Live TV',
      'movies':         'Filmy',
      'series':         'Seriály',
      'radios':         'Rádio',
      'refresh':        'Obnovit',
      'change':         'Změnit',
      'language':       'Jazyk',
      'addPlaylist':    'Přidat seznam',
      'settings':       'Nastavení',
      'about':          'O aplikaci',
      'deviceInfo':     'Info o zařízení',
      'home':           'Domů',
      'favorites':      'Oblíbené',
      'search':         'Hledat',
      'exit':           'Ukončit',
      'channels':       'kanálů',
      'films':          'filmů',
      'shows':          'seriálů',
      'radioStations':  'Rozhlasové stanice',
      'selectChannel':  'Vyberte kanál',
      'noChannels':     'Žádné kanály',
      'searchHint':     'Hledat…',
      'searchMovies':   'Hledat filmy…',
      'searchSeries':   'Hledat seriály…',
      'searchRadios':   'Hledat rádio…',
      'loading':        'Načítání…',
      'error':          'Chyba',
      'retry':          'Zkusit znovu',
      'cancel':         'Zrušit',
      'noContent':      'Žádný obsah nenalezen',
      'noSeries':       'Žádné seriály nenalezeny',
      'selectPlaylist': 'Vyberte seznam',
      'aboutApp':       'O aplikaci',
      'playlistInfo':   'Info o seznamu',
      'tapToLoad':      'Klepnutím načtěte',
      'loadingLive':    'Načítání live kanálů…',
      'loadingMovies':  'Načítání filmů…',
      'loadingSeries':  'Načítání seriálů…',
      'loadingMoment':  'U velkých serverů to může chvíli trvat',
      'noEpisodes':     'Žádné epizody',
      'season':         'Sezóna',
      'changeLanguage': 'Změnit jazyk',
      'addPlaylistHint':'Přidejte M3U URL nebo Xtream kódy pro zahájení sledování',
      'playlist':       'Seznam skladeb',
      'info':           'Info',
      'tvPrograms':     'TV programy',
      'streamError':    'Chyba streamu',
      'seasons':        'Sezóny',
      'episodes':       'Epizody',
    },

    // ── Hungarian ─────────────────────────────────────────────────────────────
    'hu': {
      'liveTV':         'Élő TV',
      'movies':         'Filmek',
      'series':         'Sorozatok',
      'radios':         'Rádió',
      'refresh':        'Frissítés',
      'change':         'Változtatás',
      'language':       'Nyelv',
      'addPlaylist':    'Lejátszólista hozzáadása',
      'settings':       'Beállítások',
      'about':          'Névjegy',
      'deviceInfo':     'Eszközinformáció',
      'home':           'Főoldal',
      'favorites':      'Kedvencek',
      'search':         'Keresés',
      'exit':           'Kilépés',
      'channels':       'csatorna',
      'films':          'film',
      'shows':          'sorozat',
      'radioStations':  'Rádióállomások',
      'selectChannel':  'Csatorna kiválasztása',
      'noChannels':     'Nincs csatorna',
      'searchHint':     'Keresés…',
      'searchMovies':   'Filmek keresése…',
      'searchSeries':   'Sorozatok keresése…',
      'searchRadios':   'Rádió keresése…',
      'loading':        'Betöltés…',
      'error':          'Hiba',
      'retry':          'Újra',
      'cancel':         'Mégse',
      'noContent':      'Nem található tartalom',
      'noSeries':       'Nem találhatók sorozatok',
      'selectPlaylist': 'Lejátszólista kiválasztása',
      'aboutApp':       'Az alkalmazásról',
      'playlistInfo':   'Lejátszólista info',
      'tapToLoad':      'Koppintson a betöltéshez',
      'loadingLive':    'Élő csatornák betöltése…',
      'loadingMovies':  'Filmek betöltése…',
      'loadingSeries':  'Sorozatok betöltése…',
      'loadingMoment':  'Nagy szerverek esetén ez egy pillanatot vehet igénybe',
      'noEpisodes':     'Nincs epizód',
      'season':         'Évad',
      'changeLanguage': 'Nyelv módosítása',
      'addPlaylistHint':'M3U URL vagy Xtream kódok hozzáadása a megtekintés megkezdéséhez',
      'playlist':       'Lejátszólista',
      'info':           'Információ',
      'tvPrograms':     'TV műsorok',
      'streamError':    'Adatfolyam-hiba',
      'seasons':        'Évadok',
      'episodes':       'Epizódok',
    },

    // ── Croatian ──────────────────────────────────────────────────────────────
    'hr': {
      'liveTV':         'Uživo TV',
      'movies':         'Filmovi',
      'series':         'Serije',
      'radios':         'Radio',
      'refresh':        'Osvježi',
      'change':         'Promijeni',
      'language':       'Jezik',
      'addPlaylist':    'Dodaj popis',
      'settings':       'Postavke',
      'about':          'O aplikaciji',
      'deviceInfo':     'Info o uređaju',
      'home':           'Početna',
      'favorites':      'Favoriti',
      'search':         'Traži',
      'exit':           'Izlaz',
      'channels':       'kanala',
      'films':          'filmova',
      'shows':          'serija',
      'radioStations':  'Radio postaje',
      'selectChannel':  'Odaberi kanal',
      'noChannels':     'Nema kanala',
      'searchHint':     'Traži…',
      'searchMovies':   'Traži filmove…',
      'searchSeries':   'Traži serije…',
      'searchRadios':   'Traži radio…',
      'loading':        'Učitavanje…',
      'error':          'Greška',
      'retry':          'Pokušaj ponovo',
      'cancel':         'Odustani',
      'noContent':      'Sadržaj nije pronađen',
      'noSeries':       'Serije nisu pronađene',
      'selectPlaylist': 'Odaberi popis',
      'aboutApp':       'O aplikaciji',
      'playlistInfo':   'Info o popisu',
      'tapToLoad':      'Dodirnite za učitavanje',
      'loadingLive':    'Učitavanje live kanala…',
      'loadingMovies':  'Učitavanje filmova…',
      'loadingSeries':  'Učitavanje serija…',
      'loadingMoment':  'Za velike servere može potrajati trenutak',
      'noEpisodes':     'Nema epizoda',
      'season':         'Sezona',
      'changeLanguage': 'Promijeni jezik',
      'addPlaylistHint':'Dodajte M3U URL ili Xtream kodove za početak gledanja',
      'playlist':       'Popis za reprodukciju',
      'info':           'Info',
      'tvPrograms':     'TV programi',
      'streamError':    'Greška streama',
      'seasons':        'Sezone',
      'episodes':       'Epizode',
    },

    // ── Bulgarian ─────────────────────────────────────────────────────────────
    'bg': {
      'liveTV':         'Живо ТВ',
      'movies':         'Филми',
      'series':         'Сериали',
      'radios':         'Радио',
      'refresh':        'Обнови',
      'change':         'Промени',
      'language':       'Език',
      'addPlaylist':    'Добави плейлист',
      'settings':       'Настройки',
      'about':          'За приложението',
      'deviceInfo':     'Инфо за устройство',
      'home':           'Начало',
      'favorites':      'Любими',
      'search':         'Търси',
      'exit':           'Изход',
      'channels':       'канала',
      'films':          'филма',
      'shows':          'сериала',
      'radioStations':  'Радиостанции',
      'selectChannel':  'Изберете канал',
      'noChannels':     'Няма канали',
      'searchHint':     'Търси…',
      'searchMovies':   'Търси филми…',
      'searchSeries':   'Търси сериали…',
      'searchRadios':   'Търси радио…',
      'loading':        'Зареждане…',
      'error':          'Грешка',
      'retry':          'Опитай отново',
      'cancel':         'Отказ',
      'noContent':      'Не е намерено съдържание',
      'noSeries':       'Не са намерени сериали',
      'selectPlaylist': 'Изберете плейлист',
      'aboutApp':       'За приложението',
      'playlistInfo':   'Инфо за плейлист',
      'tapToLoad':      'Докоснете за зареждане',
      'loadingLive':    'Зареждане на живи канали…',
      'loadingMovies':  'Зареждане на филми…',
      'loadingSeries':  'Зареждане на сериали…',
      'loadingMoment':  'За големи сървъри може да отнеме момент',
      'noEpisodes':     'Няма епизоди',
      'season':         'Сезон',
      'changeLanguage': 'Промени език',
      'addPlaylistHint':'Добавете M3U URL или Xtream кодове, за да започнете гледане',
      'playlist':       'Плейлист',
      'info':           'Инфо',
      'tvPrograms':     'ТВ програми',
      'streamError':    'Грешка на потока',
      'seasons':        'Сезони',
      'episodes':       'Епизоди',
    },

    // ── Serbian ───────────────────────────────────────────────────────────────
    'sr': {
      'liveTV':         'Uži prenos TV',
      'movies':         'Filmovi',
      'series':         'Serije',
      'radios':         'Radio',
      'refresh':        'Osveži',
      'change':         'Promeni',
      'language':       'Jezik',
      'addPlaylist':    'Dodaj listu',
      'settings':       'Podešavanja',
      'about':          'O aplikaciji',
      'deviceInfo':     'Info o uređaju',
      'home':           'Početna',
      'favorites':      'Omiljeni',
      'search':         'Pretraži',
      'exit':           'Izlaz',
      'channels':       'kanala',
      'films':          'filmova',
      'shows':          'serija',
      'radioStations':  'Radio stanice',
      'selectChannel':  'Izaberi kanal',
      'noChannels':     'Nema kanala',
      'searchHint':     'Pretraži…',
      'searchMovies':   'Pretraži filmove…',
      'searchSeries':   'Pretraži serije…',
      'searchRadios':   'Pretraži radio…',
      'loading':        'Učitavanje…',
      'error':          'Greška',
      'retry':          'Pokušaj ponovo',
      'cancel':         'Otkaži',
      'noContent':      'Sadržaj nije pronađen',
      'noSeries':       'Serije nisu pronađene',
      'selectPlaylist': 'Izaberi listu',
      'aboutApp':       'O aplikaciji',
      'playlistInfo':   'Info o listi',
      'tapToLoad':      'Dodirnite za učitavanje',
      'loadingLive':    'Učitavanje live kanala…',
      'loadingMovies':  'Učitavanje filmova…',
      'loadingSeries':  'Učitavanje serija…',
      'loadingMoment':  'Za velike servere može potrajati trenutak',
      'noEpisodes':     'Nema epizoda',
      'season':         'Sezona',
      'changeLanguage': 'Promeni jezik',
      'addPlaylistHint':'Dodajte M3U URL ili Xtream kodove za početak gledanja',
      'playlist':       'Lista za reprodukciju',
      'info':           'Info',
      'tvPrograms':     'TV programi',
      'streamError':    'Greška toka',
      'seasons':        'Sezone',
      'episodes':       'Epizode',
    },

    // ── Malay ─────────────────────────────────────────────────────────────────
    'ms': {
      'liveTV':         'TV Langsung',
      'movies':         'Filem',
      'series':         'Siri',
      'radios':         'Radio',
      'refresh':        'Muat Semula',
      'change':         'Tukar',
      'language':       'Bahasa',
      'addPlaylist':    'Tambah Senarai Main',
      'settings':       'Tetapan',
      'about':          'Tentang',
      'deviceInfo':     'Maklumat Peranti',
      'home':           'Laman Utama',
      'favorites':      'Kegemaran',
      'search':         'Cari',
      'exit':           'Keluar',
      'channels':       'saluran',
      'films':          'filem',
      'shows':          'siri',
      'radioStations':  'Stesen radio',
      'selectChannel':  'Pilih saluran',
      'noChannels':     'Tiada saluran',
      'searchHint':     'Cari…',
      'searchMovies':   'Cari filem…',
      'searchSeries':   'Cari siri…',
      'searchRadios':   'Cari radio…',
      'loading':        'Memuat…',
      'error':          'Ralat',
      'retry':          'Cuba Semula',
      'cancel':         'Batal',
      'noContent':      'Tiada kandungan ditemui',
      'noSeries':       'Tiada siri ditemui',
      'selectPlaylist': 'Pilih Senarai Main',
      'aboutApp':       'Tentang Apl',
      'playlistInfo':   'Info Senarai Main',
      'tapToLoad':      'Ketik untuk muat',
      'loadingLive':    'Memuatkan saluran langsung…',
      'loadingMovies':  'Memuatkan filem…',
      'loadingSeries':  'Memuatkan siri…',
      'loadingMoment':  'Mungkin mengambil masa untuk pelayan besar',
      'noEpisodes':     'Tiada episod',
      'season':         'Musim',
      'changeLanguage': 'Tukar Bahasa',
      'addPlaylistHint':'Tambah URL M3U atau Kod Xtream untuk mula menonton',
      'playlist':       'Senarai Main',
      'info':           'Info',
      'tvPrograms':     'Program TV',
      'streamError':    'Ralat strim',
      'seasons':        'Musim',
      'episodes':       'Episod',
    },

    // ── Indonesian ────────────────────────────────────────────────────────────
    'id': {
      'liveTV':         'TV Langsung',
      'movies':         'Film',
      'series':         'Serial',
      'radios':         'Radio',
      'refresh':        'Segarkan',
      'change':         'Ubah',
      'language':       'Bahasa',
      'addPlaylist':    'Tambah Daftar Putar',
      'settings':       'Pengaturan',
      'about':          'Tentang',
      'deviceInfo':     'Info Perangkat',
      'home':           'Beranda',
      'favorites':      'Favorit',
      'search':         'Cari',
      'exit':           'Keluar',
      'channels':       'saluran',
      'films':          'film',
      'shows':          'serial',
      'radioStations':  'Stasiun radio',
      'selectChannel':  'Pilih saluran',
      'noChannels':     'Tidak ada saluran',
      'searchHint':     'Cari…',
      'searchMovies':   'Cari film…',
      'searchSeries':   'Cari serial…',
      'searchRadios':   'Cari radio…',
      'loading':        'Memuat…',
      'error':          'Kesalahan',
      'retry':          'Coba Lagi',
      'cancel':         'Batal',
      'noContent':      'Tidak ada konten ditemukan',
      'noSeries':       'Tidak ada serial ditemukan',
      'selectPlaylist': 'Pilih Daftar Putar',
      'aboutApp':       'Tentang Aplikasi',
      'playlistInfo':   'Info Daftar Putar',
      'tapToLoad':      'Ketuk untuk memuat',
      'loadingLive':    'Memuat saluran langsung…',
      'loadingMovies':  'Memuat film…',
      'loadingSeries':  'Memuat serial…',
      'loadingMoment':  'Ini mungkin membutuhkan waktu untuk server besar',
      'noEpisodes':     'Tidak ada episode',
      'season':         'Musim',
      'changeLanguage': 'Ubah Bahasa',
      'addPlaylistHint':'Tambahkan URL M3U atau Kode Xtream untuk mulai menonton',
      'playlist':       'Daftar Putar',
      'info':           'Info',
      'tvPrograms':     'Program TV',
      'streamError':    'Kesalahan aliran',
      'seasons':        'Musim',
      'episodes':       'Episode',
    },

    // ── Vietnamese ────────────────────────────────────────────────────────────
    'vi': {
      'liveTV':         'TV Trực tiếp',
      'movies':         'Phim',
      'series':         'Phim bộ',
      'radios':         'Đài radio',
      'refresh':        'Làm mới',
      'change':         'Thay đổi',
      'language':       'Ngôn ngữ',
      'addPlaylist':    'Thêm danh sách phát',
      'settings':       'Cài đặt',
      'about':          'Giới thiệu',
      'deviceInfo':     'Thông tin thiết bị',
      'home':           'Trang chủ',
      'favorites':      'Yêu thích',
      'search':         'Tìm kiếm',
      'exit':           'Thoát',
      'channels':       'kênh',
      'films':          'phim',
      'shows':          'bộ phim',
      'radioStations':  'Đài phát thanh',
      'selectChannel':  'Chọn kênh',
      'noChannels':     'Không có kênh',
      'searchHint':     'Tìm kiếm…',
      'searchMovies':   'Tìm kiếm phim…',
      'searchSeries':   'Tìm kiếm phim bộ…',
      'searchRadios':   'Tìm kiếm radio…',
      'loading':        'Đang tải…',
      'error':          'Lỗi',
      'retry':          'Thử lại',
      'cancel':         'Hủy',
      'noContent':      'Không tìm thấy nội dung',
      'noSeries':       'Không tìm thấy phim bộ',
      'selectPlaylist': 'Chọn danh sách phát',
      'aboutApp':       'Giới thiệu ứng dụng',
      'playlistInfo':   'Thông tin danh sách phát',
      'tapToLoad':      'Nhấn để tải',
      'loadingLive':    'Đang tải kênh trực tiếp…',
      'loadingMovies':  'Đang tải phim…',
      'loadingSeries':  'Đang tải phim bộ…',
      'loadingMoment':  'Điều này có thể mất một lúc đối với máy chủ lớn',
      'noEpisodes':     'Không có tập phim',
      'season':         'Mùa',
      'changeLanguage': 'Đổi ngôn ngữ',
      'addPlaylistHint':'Thêm URL M3U hoặc mã Xtream để bắt đầu xem',
      'playlist':       'Danh sách phát',
      'info':           'Thông tin',
      'tvPrograms':     'Chương trình TV',
      'streamError':    'Lỗi luồng',
      'seasons':        'Các mùa',
      'episodes':       'Tập phim',
    },

    // ── Hindi ─────────────────────────────────────────────────────────────────
    'hi': {
      'liveTV':         'लाइव टीवी',
      'movies':         'फिल्में',
      'series':         'सीरीज',
      'radios':         'रेडियो',
      'refresh':        'रीफ्रेश',
      'change':         'बदलें',
      'language':       'भाषा',
      'addPlaylist':    'प्लेलिस्ट जोड़ें',
      'settings':       'सेटिंग्स',
      'about':          'के बारे में',
      'deviceInfo':     'डिवाइस जानकारी',
      'home':           'होम',
      'favorites':      'पसंदीदा',
      'search':         'खोजें',
      'exit':           'बाहर निकलें',
      'channels':       'चैनल',
      'films':          'फिल्में',
      'shows':          'शो',
      'radioStations':  'रेडियो स्टेशन',
      'selectChannel':  'चैनल चुनें',
      'noChannels':     'कोई चैनल नहीं',
      'searchHint':     'खोजें…',
      'searchMovies':   'फिल्में खोजें…',
      'searchSeries':   'सीरीज खोजें…',
      'searchRadios':   'रेडियो खोजें…',
      'loading':        'लोड हो रहा है…',
      'error':          'त्रुटि',
      'retry':          'पुनः प्रयास',
      'cancel':         'रद्द करें',
      'noContent':      'कोई सामग्री नहीं मिली',
      'noSeries':       'कोई सीरीज नहीं मिली',
      'selectPlaylist': 'प्लेलिस्ट चुनें',
      'aboutApp':       'ऐप के बारे में',
      'playlistInfo':   'प्लेलिस्ट जानकारी',
      'tapToLoad':      'लोड करने के लिए टैप करें',
      'loadingLive':    'लाइव चैनल लोड हो रहे हैं…',
      'loadingMovies':  'फिल्में लोड हो रही हैं…',
      'loadingSeries':  'सीरीज लोड हो रही हैं…',
      'loadingMoment':  'बड़े सर्वर के लिए इसमें कुछ समय लग सकता है',
      'noEpisodes':     'कोई एपिसोड नहीं',
      'season':         'सीजन',
      'changeLanguage': 'भाषा बदलें',
      'addPlaylistHint':'देखना शुरू करने के लिए M3U URL या Xtream कोड जोड़ें',
      'playlist':       'प्लेलिस्ट',
      'info':           'जानकारी',
      'tvPrograms':     'टीवी कार्यक्रम',
      'streamError':    'स्ट्रीम त्रुटि',
      'seasons':        'सीजन',
      'episodes':       'एपिसोड',
    },

    // ── Hebrew ────────────────────────────────────────────────────────────────
    'he': {
      'liveTV':         'טלוויזיה חיה',
      'movies':         'סרטים',
      'series':         'סדרות',
      'radios':         'רדיו',
      'refresh':        'רענן',
      'change':         'שנה',
      'language':       'שפה',
      'addPlaylist':    'הוסף רשימת השמעה',
      'settings':       'הגדרות',
      'about':          'אודות',
      'deviceInfo':     'מידע על מכשיר',
      'home':           'בית',
      'favorites':      'מועדפים',
      'search':         'חיפוש',
      'exit':           'יציאה',
      'channels':       'ערוצים',
      'films':          'סרטים',
      'shows':          'סדרות',
      'radioStations':  'תחנות רדיו',
      'selectChannel':  'בחר ערוץ',
      'noChannels':     'אין ערוצים',
      'searchHint':     'חיפוש…',
      'searchMovies':   'חפש סרטים…',
      'searchSeries':   'חפש סדרות…',
      'searchRadios':   'חפש רדיו…',
      'loading':        'טוען…',
      'error':          'שגיאה',
      'retry':          'נסה שוב',
      'cancel':         'ביטול',
      'noContent':      'לא נמצא תוכן',
      'noSeries':       'לא נמצאו סדרות',
      'selectPlaylist': 'בחר רשימת השמעה',
      'aboutApp':       'אודות האפליקציה',
      'playlistInfo':   'מידע על רשימה',
      'tapToLoad':      'הקש לטעינה',
      'loadingLive':    'טוען ערוצים חיים…',
      'loadingMovies':  'טוען סרטים…',
      'loadingSeries':  'טוען סדרות…',
      'loadingMoment':  'זה עשוי לקחת רגע עבור שרתים גדולים',
      'noEpisodes':     'אין פרקים',
      'season':         'עונה',
      'changeLanguage': 'שנה שפה',
      'addPlaylistHint':'הוסף URL M3U או קודי Xtream כדי להתחיל לצפות',
      'playlist':       'רשימת השמעה',
      'info':           'מידע',
      'tvPrograms':     'תוכניות טלוויזיה',
      'streamError':    'שגיאת זרם',
      'seasons':        'עונות',
      'episodes':       'פרקים',
    },

    // ── Urdu ──────────────────────────────────────────────────────────────────
    'ur': {
      'liveTV':         'لائیو ٹی وی',
      'movies':         'فلمیں',
      'series':         'سیریز',
      'radios':         'ریڈیو',
      'refresh':        'ریفریش',
      'change':         'تبدیل کریں',
      'language':       'زبان',
      'addPlaylist':    'پلے لسٹ شامل کریں',
      'settings':       'ترتیبات',
      'about':          'کے بارے میں',
      'deviceInfo':     'ڈیوائس کی معلومات',
      'home':           'ہوم',
      'favorites':      'پسندیدہ',
      'search':         'تلاش',
      'exit':           'باہر نکلیں',
      'channels':       'چینلز',
      'films':          'فلمیں',
      'shows':          'شوز',
      'radioStations':  'ریڈیو اسٹیشن',
      'selectChannel':  'چینل منتخب کریں',
      'noChannels':     'کوئی چینل نہیں',
      'searchHint':     'تلاش کریں…',
      'searchMovies':   'فلمیں تلاش کریں…',
      'searchSeries':   'سیریز تلاش کریں…',
      'searchRadios':   'ریڈیو تلاش کریں…',
      'loading':        'لوڈ ہو رہا ہے…',
      'error':          'خرابی',
      'retry':          'دوبارہ کوشش',
      'cancel':         'منسوخ',
      'noContent':      'کوئی مواد نہیں ملا',
      'noSeries':       'کوئی سیریز نہیں ملی',
      'selectPlaylist': 'پلے لسٹ منتخب کریں',
      'aboutApp':       'ایپ کے بارے میں',
      'playlistInfo':   'پلے لسٹ کی معلومات',
      'tapToLoad':      'لوڈ کرنے کے لیے ٹیپ کریں',
      'loadingLive':    'لائیو چینلز لوڈ ہو رہے ہیں…',
      'loadingMovies':  'فلمیں لوڈ ہو رہی ہیں…',
      'loadingSeries':  'سیریز لوڈ ہو رہی ہیں…',
      'loadingMoment':  'بڑے سرورز کے لیے اس میں کچھ وقت لگ سکتا ہے',
      'noEpisodes':     'کوئی ایپیسوڈ نہیں',
      'season':         'سیزن',
      'changeLanguage': 'زبان تبدیل کریں',
      'addPlaylistHint':'دیکھنا شروع کرنے کے لیے M3U URL یا Xtream کوڈز شامل کریں',
      'playlist':       'پلے لسٹ',
      'info':           'معلومات',
      'tvPrograms':     'ٹی وی پروگرام',
      'streamError':    'اسٹریم خرابی',
      'seasons':        'سیزنز',
      'episodes':       'ایپیسوڈز',
    },

    // ── Thai ──────────────────────────────────────────────────────────────────
    'th': {
      'liveTV':         'ทีวีสด',
      'movies':         'ภาพยนตร์',
      'series':         'ซีรีส์',
      'radios':         'วิทยุ',
      'refresh':        'รีเฟรช',
      'change':         'เปลี่ยน',
      'language':       'ภาษา',
      'addPlaylist':    'เพิ่มเพลย์ลิสต์',
      'settings':       'การตั้งค่า',
      'about':          'เกี่ยวกับ',
      'deviceInfo':     'ข้อมูลอุปกรณ์',
      'home':           'หน้าแรก',
      'favorites':      'รายการโปรด',
      'search':         'ค้นหา',
      'exit':           'ออก',
      'channels':       'ช่อง',
      'films':          'ภาพยนตร์',
      'shows':          'ซีรีส์',
      'radioStations':  'สถานีวิทยุ',
      'selectChannel':  'เลือกช่อง',
      'noChannels':     'ไม่มีช่อง',
      'searchHint':     'ค้นหา…',
      'searchMovies':   'ค้นหาภาพยนตร์…',
      'searchSeries':   'ค้นหาซีรีส์…',
      'searchRadios':   'ค้นหาวิทยุ…',
      'loading':        'กำลังโหลด…',
      'error':          'ข้อผิดพลาด',
      'retry':          'ลองใหม่',
      'cancel':         'ยกเลิก',
      'noContent':      'ไม่พบเนื้อหา',
      'noSeries':       'ไม่พบซีรีส์',
      'selectPlaylist': 'เลือกเพลย์ลิสต์',
      'aboutApp':       'เกี่ยวกับแอป',
      'playlistInfo':   'ข้อมูลเพลย์ลิสต์',
      'tapToLoad':      'แตะเพื่อโหลด',
      'loadingLive':    'กำลังโหลดช่องสด…',
      'loadingMovies':  'กำลังโหลดภาพยนตร์…',
      'loadingSeries':  'กำลังโหลดซีรีส์…',
      'loadingMoment':  'อาจใช้เวลาสักครู่สำหรับเซิร์ฟเวอร์ขนาดใหญ่',
      'noEpisodes':     'ไม่มีตอน',
      'season':         'ซีซัน',
      'changeLanguage': 'เปลี่ยนภาษา',
      'addPlaylistHint':'เพิ่ม URL M3U หรือรหัส Xtream เพื่อเริ่มดู',
      'playlist':       'เพลย์ลิสต์',
      'info':           'ข้อมูล',
      'tvPrograms':     'รายการทีวี',
      'streamError':    'ข้อผิดพลาดสตรีม',
      'seasons':        'ซีซัน',
      'episodes':       'ตอน',
    },

    // ── Slovak ────────────────────────────────────────────────────────────────
    'sk': {
      'liveTV':         'Live TV',
      'movies':         'Filmy',
      'series':         'Seriály',
      'radios':         'Rádio',
      'refresh':        'Obnoviť',
      'change':         'Zmeniť',
      'language':       'Jazyk',
      'addPlaylist':    'Pridať zoznam',
      'settings':       'Nastavenia',
      'about':          'O aplikácii',
      'deviceInfo':     'Info o zariadení',
      'home':           'Domov',
      'favorites':      'Obľúbené',
      'search':         'Hľadať',
      'exit':           'Ukončiť',
      'channels':       'kanálov',
      'films':          'filmov',
      'shows':          'seriálov',
      'radioStations':  'Rozhlasové stanice',
      'selectChannel':  'Vyberte kanál',
      'noChannels':     'Žiadne kanály',
      'searchHint':     'Hľadať…',
      'searchMovies':   'Hľadať filmy…',
      'searchSeries':   'Hľadať seriály…',
      'searchRadios':   'Hľadať rádio…',
      'loading':        'Načítavanie…',
      'error':          'Chyba',
      'retry':          'Skúsiť znova',
      'cancel':         'Zrušiť',
      'noContent':      'Žiadny obsah nenájdený',
      'noSeries':       'Žiadne seriály nenájdené',
      'selectPlaylist': 'Vybrať zoznam',
      'aboutApp':       'O aplikácii',
      'playlistInfo':   'Info o zozname',
      'tapToLoad':      'Klepnutím načítajte',
      'loadingLive':    'Načítavanie live kanálov…',
      'loadingMovies':  'Načítavanie filmov…',
      'loadingSeries':  'Načítavanie seriálov…',
      'loadingMoment':  'Pre veľké servery to môže chvíľu trvať',
      'noEpisodes':     'Žiadne epizódy',
      'season':         'Séria',
      'changeLanguage': 'Zmeniť jazyk',
      'addPlaylistHint':'Pridajte M3U URL alebo Xtream kódy na začatie sledovania',
      'playlist':       'Zoznam skladieb',
      'info':           'Info',
      'tvPrograms':     'TV programy',
      'streamError':    'Chyba streamu',
      'seasons':        'Série',
      'episodes':       'Epizódy',
    },
  };
}
